function [ fh ] = bsc_quickPlot(fg, color)
% [ fh ] = bsc_quickPlot(fg, color)
%
% inputs
% fg = fiber group of standard structure which is to be plotted
% color = uniform color (of format [x,y,z], where x y and z are all values
% between 0 and 1 to be used for the lines of the plot, defaults to a
% random color
%
% outputs:
% fh = a figure handle for the figure object generated by this script
%% begin code
%arbitrarily assign a color.  Note, fg has a color field, but we needn't
%assume this.
if notDefined('color')
    color=[rand(1),rand(1),rand(1)];
end

axis equal
hold on

%loop over streamlines
for ifiblength= 1:length(fg.fibers)
    
    plot3(fg.fibers{ifiblength}(1,:),fg.fibers{ifiblength}(2,:),fg.fibers{ifiblength}(3,:),'Color',color,'linewidth',1);
    
    if ifiblength==1
        hold on
    end
    
end
%add a name if you can
if isfield(fg, 'name')
    if ~isempty(fg.name)
        %replace underscores, because matlab does weird things in title
        %names with underscores
        nameHold=strrep(fg.name,'_',' ');
        title(strcat('Plot of ', nameHold));
    end
end

xlabel('X coordinates');
ylabel('Y coordinates');
zlabel('Z coordinates');

fh=gcf;
end

